[package]
name = "ronq"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "rq"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
colored = "3.0.0"
ron = "0.12.0"
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.10"
